config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('newsapp.urls',)),
]

newsapp/urls.py
from .views import SettingCreateView, SettingUpdateView, indexfunc, listfunc, settingConf
from django.urls import path

urlpatterns = [
    path('', indexfunc, name='index'),
    path('list/',listfunc,name='list'),
    path('setting/',settingConf, name='settingConf'),
    path('settingCreate/',SettingCreateView.as_view(), name='create'),
    path('settingUpdate/<uuid:pk>/',SettingUpdateView.as_view(), name='update'),
]

newsapp/models.py
from django.db import models
from accounts.models import User

# Create your models here.


class Setting(models.Model):
    id = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    key1 = models.CharField(max_length=15,blank=False,default='未登録')
    key2 = models.CharField(max_length=15,blank=True,default='未登録')
    key3 = models.CharField(max_length=15,blank=True,default='未登録')
    site1 = models.BooleanField(default=True)
    site2 = models.BooleanField(default=True)
    site3 = models.BooleanField(default=True)
    site4 = models.BooleanField(default=True)
    site5 = models.BooleanField(default=True)
    
    def __str__(self):
        return str(self.id) + 'の設定'

newsapp/forms.py
from django import forms
from .models import Setting



class SettingForm(forms.ModelForm):
    class Meta:
        model = Setting
        fields = ('key1', 'key2', 'key3',\
            'site1', 'site2', 'site3', 'site4','site5',)
        
        
        labels = {
            'key1': 'キーワード1',
            'key2': 'キーワード2',
            'key3': 'キーワード3',
            'site1': 'yahoo!ニュース',
            'site2': '日経電子版',
            'site3': '株探（材料）',
            'site4': '株探（決算）',
            'site5': '時事ドットコム',
        }
        widgets = {
            'site1': forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'site2': forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'site3': forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'site4': forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'site5': forms.CheckboxInput(attrs={'class':'form-check-input'}),
        }
        
    def clean(self):
        cleaned_data = super(SettingForm, self).clean()
        site1 = self.cleaned_data.get('site1')
        site2 = self.cleaned_data.get('site2')
        site3 = self.cleaned_data.get('site3')
        site4 = self.cleaned_data.get('site4')
        site5 = self.cleaned_data.get('site5')
        if site1==False and site2==False and site3==False and site4==False and site5==False:
            raise forms.ValidationError("検索対象サイトを最低１つ選択してください。")
        return cleaned_data

newsapp/views.py
from django.urls.base import reverse, reverse_lazy
from newsapp.forms import SettingForm
from newsapp.models import Setting
from allauth.account.decorators import verified_email_required
from bs4 import BeautifulSoup
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView
import requests
import re
from concurrent.futures import ThreadPoolExecutor
from urllib.parse import urlencode
from django.contrib import messages


# Create your views here.
#キーワード未登録者は設定に誘導
@verified_email_required
def indexfunc(request):
    if Setting.objects.filter(id=request.user.id).values_list('key1',flat=True).exists():
        redirect_url = reverse('list')
        param = urlencode({'key':Setting.objects.values_list('key1',flat=True).get(id=request.user.id)})
        url = f'{redirect_url}?{param}'
        return redirect(url)
    else:
        return redirect('create')
        

@verified_email_required
def listfunc(request):         
    data = Setting.objects.filter(id=request.user).all()
    key = ''
    res = ''
    i = 1 #yahoo
    j = 1 #日経
    k = 1 #ORICON
    
    newsTitle1=[] 
    newsLink1=[]
    newsTime1=[]
    newsData1=[]
    
    newsTitle2=[] 
    newsLink2=[]
    newsTime2=[]
    newsData2=[]
    
    newsTitle3=[] 
    newsLink3=[]
    newsTime3=[]
    newsData3=[]
    
    newsTitle4=[] 
    newsLink4=[]
    newsTime4=[]
    newsData4=[]
    
    newsTitle5=[] 
    newsLink5=[]
    newsTime5=[]
    newsData5=[]
    
    if 'key' in request.GET:
        key = request.GET['key']
        
    while i<=5 and j<=421 and k<=5:
        
        urls1 = ['https://news.yahoo.co.jp/topics/top-picks?page=' + str(i),    #site1
                'https://www.nikkei.com/news/category/?bn=' + str(j),           #site3
                'https://www.oricon.co.jp/category/interest/p/' + str(k) + '/', #site4
        ]
        
        #マルチスレッディングでrequests
        #ページ遷移でスクレイピング(ループ処理)
        with ThreadPoolExecutor(2) as executor:
            res = list(executor.map(requests.get,urls1))
            
            #yahooニュース(site1)
            if Setting.objects.filter(id=request.user.id).values_list('site1',flat=True):    
                soup = BeautifulSoup(res[0].content, 'lxml')
                
                elems = soup.find_all('div',class_='newsFeed_item_title', text=re.compile(key))
                for elem in elems:
                    newsTitle1.append(elem.text)
                    newsLink1.append(elem.parent.parent.get('href'))
                    newsTime1.append(elem.next_sibling.text)
                
                i += 1
                
            #日経電子版(site3)
            if Setting.objects.filter(id=request.user.id).values_list('site3',flat=True):
                soup = BeautifulSoup(res[1].content, 'lxml')

                elems = soup.find_all('a',href=re.compile('/article/'),text=re.compile(key))
                
                for elem in elems:
                    if elem.find_parent('span'):
                        newsTitle3.append(elem.text)
                        newsLink3.append('https://www.nikkei.com/' + elem.get('href'))
                        newsTime3.append(elem.find_parent().find_next_sibling().findChild('span').text)
                
                j += 30    
        

            #ORICON NEWS(site4)
            if Setting.objects.filter(id=request.user.id).values_list('site4',flat=True):
                soup = BeautifulSoup(res[2].content, 'lxml')

                elems = soup.find_all('h2',class_='title',text=re.compile(key))
                
                for elem in elems:
                    newsTitle4.append(elem.text)
                    newsLink4.append('https://www.oricon.co.jp' + elem.find_parent('a').get('href'))
                    newsTime4.append(elem.find_parent(class_='card-body').find_next_sibling(class_='card-footer').find(class_='en').text)
                
                k += 1
                
        urls2 = ['https://www.jiji.com/jc/list?g=news',#site2
                'https://www.nikkansports.com/news/',  #site5
        ]
            
    #時事ドットコム(site2)
    if Setting.objects.filter(id=request.user.id).values_list('site2',flat=True):
        res = requests.get(urls2[0])
        soup = BeautifulSoup(res.content, 'lxml')

        elems = soup.find_all('p',text=re.compile(key))
            
        for elem in elems:
            if elem.find_next_sibling(): 
                newsTitle2.append(elem.text)
                newsLink2.append('https://www.jiji.com' + elem.parent.get('href'))
                newsTime2.append(elem.find_next_sibling().text)
            else:
                pass
            
    #日刊スポーツ(site5)
    if Setting.objects.filter(id=request.user.id).values_list('site5',flat=True):
        res = requests.get(urls2[1])
        soup = BeautifulSoup(res.content, 'lxml')

        elems = soup.find_all('a',href=re.compile('https://www.nikkansports.com/'),text=re.compile(key))
        for elem in elems:
            if elem.find_next_sibling():
                newsTitle5.append(elem.text)
                newsLink5.append(elem.get('href'))
                newsTime5.append(elem.find_next_sibling().text)
            else:
                pass
    
    for i,_ in enumerate(newsTitle1):
        newsData1.append({
            'newsTitle1': newsTitle1[i],
            'newsLink1': newsLink1[i],
            'newsTime1': newsTime1[i],
        })
    for i,_ in enumerate(newsTitle2):
        newsData2.append({
            'newsTitle2': newsTitle2[i],
            'newsLink2': newsLink2[i],
            'newsTime2': newsTime2[i],
        })
    for i,_ in enumerate(newsTitle3):
        newsData3.append({
            'newsTitle3': newsTitle3[i],
            'newsLink3': newsLink3[i],
            'newsTime3': newsTime3[i],
        })
    for i,_ in enumerate(newsTitle4):
        newsData4.append({
            'newsTitle4': newsTitle4[i],
            'newsLink4': newsLink4[i],
            'newsTime4': newsTime4[i],
        })
    for i,_ in enumerate(newsTitle5):
        newsData5.append({
            'newsTitle5': newsTitle5[i],
            'newsLink5': newsLink5[i],
            'newsTime5': newsTime5[i],
        })
        
    newsCount1 = len(newsTitle1)
    newsCount2 = len(newsTitle2)
    newsCount3 = len(newsTitle3)
    newsCount4 = len(newsTitle4)
    newsCount5 = len(newsTitle5)
    
    context = {
        #ログインユーザーの設定値
        'data': data,
        #ニュースデータ
        'newsData1': newsData1,
        'newsData2': newsData2,
        'newsData3': newsData3,
        'newsData4': newsData4,
        'newsData5': newsData5,
        'newsCount1': newsCount1,
        'newsCount2': newsCount2,
        'newsCount3': newsCount3,
        'newsCount4': newsCount4,
        'newsCount5': newsCount5,
    }
        
    return render(request, 'newsapp/list.html', context,)

@verified_email_required
#設定ルート分岐
def settingConf(request):
    if Setting.objects.filter(id=request.user.id).exists():
        return redirect('update',pk=request.user.pk)
    else:
        return redirect('create')
        

#設定(初回登録)
class SettingCreateView(LoginRequiredMixin,CreateView):
    model = Setting
    form_class = SettingForm
    template_name = 'newsapp/setting.html'
    success_url = reverse_lazy('index')
    
    # def get_success_url(self):
    #     return reverse('update', kwargs={'pk':self.object.pk})
    
    def form_valid(self, form):
        qryset =  form.save(commit=False)
        qryset.id = self.request.user
        if qryset.key2 == '':
            qryset.key2 = '未登録'
        if qryset.key3 == '':
            qryset.key3 = '未登録'
        qryset.save()
        messages.success(self.request, '登録完了しました。')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, '登録完了できません。')
        return super().form_invalid(form)
    
    
#設定（更新）
class SettingUpdateView(LoginRequiredMixin,UpdateView):
    model = Setting
    form_class = SettingForm
    template_name ='newsapp/setting.html'
    success_url = reverse_lazy('index')
    
    # def get_success_url(self):
    #     return reverse('update',kwargs={'pk':self.object.pk})
    
    def form_valid(self, form):
        qryset = form.save(commit=False)
        qryset.id = self.request.user
        if qryset.key2 == '':
            qryset.key2 = '未登録'
        if qryset.key3 == '':
            qryset.key3 = '未登録'
        qryset.save()
        messages.success(self.request, '設定を更新しました。')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, '設定を更新できません。')
        return super().form_invalid(form)

templates/newsapp/list.html
{% extends 'base.html' %}
{% block title %}ニュース一覧{% endblock title %}
{% block h1 %}ニュース一覧{% endblock h1 %}
{% block content %}
  {% load static %}
  <link href="{% static 'css/list.css' %}" rel="stylesheet">
  {% if messages %}
    <ul class="messages_ul">
      {% for message in messages %}
        <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% for setting in data %}
    <ul class="nav nav-tabs bg-light">
      <li class="nav-item">
        <a class="nav-link" id="key1" href="?key={{ setting.key1 }}"><i class="fas fa-search"></i>[{{ setting.key1 }}]</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="key2" {% if setting.key2 == '未登録' %}href="{% url 'settingConf' %}"{% else %}href="?key={{ setting.key2 }}"{% endif %}><i class="fas fa-search"></i>[{{ setting.key2 }}]</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="key3" {% if setting.key3 == '未登録' %}href="{% url 'settingConf' %}"{% else %}href="?key={{ setting.key3 }}"{% endif %}><i class="fas fa-search"></i>[{{ setting.key3 }}]</a>
      </li>
    </ul>
    {% if setting.site1 %}
      <table class="table bg-light">
        <thead class="table-dark">
          <tr>
            <th class="th-1">Yahoo!ニュース</th><th class="th-2">{{newsCount1}}件ヒット</th>
          </tr>
        </thead>
        <tbody>
          {% if newsData1 %}
            {% for site1 in newsData1 %}
              <tr>
                <td><a href="{{site1.newsLink1}}" target="_blank">{{site1.newsTitle1}}</a></td><td>{{site1.newsTime1}}</td>
              </tr>
            {% endfor %}
          {% else %}
              <td><p>現在該当のニュースはありません。</p></td><td>&nbsp;</td>
          {% endif %}
        </tbody>
      </table>
    {% endif %}
    {% if setting.site2 %}
      <table class="table bg-light">
        <thead class="table-dark">
          <tr>
            <th class="th-1">時事ドットネット</th><th class="th-2">{{newsCount2}}件ヒット</th>
          </tr>
        </thead>
        <tbody>
          {% if newsData2 %}
            {% for site2 in newsData2 %}
              <tr>
                <td><a href="{{site2.newsLink2}}" target="_blank">{{site2.newsTitle2}}</a></td><td>{{site2.newsTime2}}</td>
              </tr>
            {% endfor %}
          {% else %}
              <td><p>現在該当のニュースはありません。</p></td>&nbsp;</td>
          {% endif %}
        </tbody>
      </table>
    {% endif %}
    {% if setting.site3 %}
      <table class="table bg-light">
        <thead class="table-dark">
          <tr>
            <th class="th-1">日本経済新聞（日経電子版）</th><th class="th-2">{{newsCount3}}件ヒット</th>
          </tr>
        </thead>
        <tbody>
          {% if newsData3 %}
            {% for site3 in newsData3 %}
              <tr>
                <td><a href="{{site3.newsLink3}}" target="_blank">{{site3.newsTitle3}}</a></td><td>{{site3.newsTime3}}</td>
              </tr>
            {% endfor %}
          {% else %}
              <td><p>現在該当のニュースはありません。</p></td><td>&nbsp;</td>
          {% endif %}
        </tbody>
      </table>
    {% endif %}
    {% if setting.site4 %}
      <table class="table bg-light">
        <thead class="table-dark">
          <tr>
            <th class="th-1">ORICON NEWS</th><th class="th-2">{{newsCount4}}件ヒット</th>
          </tr>
        </thead>
        <tbody>
          {% if newsData4 %}
            {% for site4 in newsData4 %}
              <tr>
                <td><a href="{{site4.newsLink4}}" target="_blank">{{site4.newsTitle4}}</a></td><td>{{site4.newsTime4}}</td>
              </tr>
            {% endfor %}
          {% else %}
              <td><p>現在該当のニュースはありません。</p></td><td>&nbsp;</td>
          {% endif %}
        </tbody>
      </table>
    {% endif %}
    {% if setting.site5 %}
      <table class="table bg-light">
        <thead class="table-dark">
          <tr>
            <th class="th-1">日刊スポーツ</th><th class="th-2">{{newsCount5}}件ヒット</th>
          </tr>
        </thead>
        <tbody>
          {% if newsData5 %}
            {% for site5 in newsData5 %}
              <tr>
                <td><a href="{{site5.newsLink5}}" target="_blank">{{site5.newsTitle5}}</a></td><td>{{site5.newsTime5}}</td>
              </tr>
            {% endfor %}
          {% else %}
              <td><p>現在該当のニュースはありません。</p></td><td>&nbsp;</td>
          {% endif %}
        </tbody>
      </table>
    {% endif %}
  {% endfor %}
{% endblock content %}

templates/newsapp/setting.html
{% extends 'base.html' %}
{% block title %}設定{% endblock title %}
{% block h1 %}設定{% endblock h1 %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/setting.css' %}" rel="stylesheet">
    {% if messages %}
        <ul class="messages_ul">
            {% for message in messages %}
                <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST">{% csrf_token %}
        <h4>・検索キーワード</h4>
        <p class="text-warning">任意のキーワードを最低１つ登録してください</p>
        <div class="mb-3">
            <label for="id_key1" class="form-label">キーワード1（入力必須）</label>
            <input type="text" class="form-control" id="id_key1" placeholder="キーワード" name="key1" value="{{form.key1.value}}">
        </div>
        {% if form.key1.errors %}
            <div class="alert alert-danger" role="alert">
                {{form.key1.errors}}
            </div>
        {% endif %}
        <div class="mb-3">
            <label for="id_key2" class="form-label">キーワード2</label>
            <input type="text" class="form-control" id="id_key2" placeholder="キーワード" name="key2" value="{{form.key2.value}}">
        </div>
        <div class="mb-3">
            <label for="id_key3" class="form-label">キーワード3</label>
            <input type="text" class="form-control" id="id_key3" placeholder="キーワード" name="key3" value="{{form.key3.value}}">
        </div>
        <h4 id="h4-site">・検索対象サイト</h4>
        <ul class="list-group">
            <li class="list-group-item bg-primary">
                <p class="text-light">時事系 - current events</p>
            </li>
            <li class="list-group-item">
                <div class="form-check form-switch">
                {{ form.site1 }}
                <label class="form-check-label" for="id_site1">yahoo!ニュース</label>
                </div>
            </li>
            <li class="list-group-item">
                <div class="form-check form-switch">
                {{ form.site2 }}
                <label class="form-check-label" for="id_site2">時事ドットコム</label>
                </div>
            </li>
            <li class="list-group-item bg-dark">
                <p class="text-light">経済系 - economy</p>
            </li>
            <li class="list-group-item">
                <div class="form-check form-switch">
                {{ form.site3 }}
                <label class="form-check-label" for="id_site3">日本経済新聞</label>
                </div>
            </li>
            <li class="list-group-item bg-warning">
                <p class="text-light">趣味系 - hobby</p>
            </li>
            <li class="list-group-item">
                <div class="form-check form-switch">
                {{ form.site4 }}
                <label class="form-check-label" for="id_site4">ORICON NEWS</label>
                </div>
            </li>
            <li class="list-group-item bg-info">
                <p class="text-light">スポーツ系 - sports</p>
            </li>
            <li class="list-group-item">
                <div class="form-check form-switch">
                {{ form.site5 }}
                <label class="form-check-label" for="id_site5">日刊スポーツ</label>
                </div>
            </li>
        </ul>
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {{form.non_field_errors}}
            </div>
        {% endif %}
        <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-success" type="submit">登録 <i class="fas fa-check"></i></button>
            <a class="btn btn-secondary" href="{% url 'index' %}" role="button">ニュース一覧へ <i class="far fa-newspaper"></i></a>
        </div><br>
    </form>
{% endblock content %}